# This workflow will deploy a PowerShell project to an Azure Functions App on Windows or Linux when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure Functions app.
# For instructions see https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-powershell
#
# To configure this workflow:
# 1. Set up the following secrets in your repository:
#   - AZURE_FUNCTIONAPP_PUBLISH_PROFILE
# 2. Change env variables for your configuration.

name: Deploy PowerShell project to Azure Function App

on:
  push:
    branches:
      - ["master"]

env:
  AZURE_FUNCTIONAPP_NAME: "AZITGSecureScore" # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # set this to the path to your function app project, defaults to the repository root
  #env_var: '' # Set the environment variable for unique variables for this workflow.

jobs:
  build-and-deploy:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    environment: dev
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      #substitute production appsettings entries to appsettings json file
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: "${{env.DOTNET_ROOT}}/myapp/appsettings.json"
        env:
          ApplicationId: ${{ secrets.ApplicationId }}
          ApplicationSecret: ${{ secrets.ApplicationSecret}}
          Description: ${{secrets.Description}}
          ExchangeRefreshToken: ${{secrets.ExchangeRefreshToken}}
          FlexAssetName: ${{secrets.FlexAssetName}}
          ITGApiKey: ${{secrets.ITGApiKey}}
          RefreshToken: ${{secrets.RefreshToken}}
          TenandId: ${{secrets.TenandId}}
          UPN: ${{secrets.UPN}}
          ApiEndpoint: $${{secrets.ApiEndpoint}}

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # Remove publish-profile to use Azure RBAC
