name: "Create new Function App"

on:
  workflow_dispatch:
    inputs:
      bicepFilePath:
        description: Bicep Template. Path to the bicep file
        required: true
        default: "./deployment/main.deploy.bicep"
      azureRegion:
        description: Azure Region. Please provide desired Azure Region shortname.
        required: true
        default: "westus"
      azureAppName:
        description: Azure App Name. All resources will have this in their name.
        required: true
        default: "azitgluefunctions"
    branches:
      - master

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v3
      - name: Run Bicep Linter
        run: az bicep build --file ${{ inputs.bicepFilePath }}
        shell: bash
  build-and-deploy:
    runs-on: ubuntu-latest # For Linux, use ubuntu-latest
    needs: linter
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Create Resource Group
        uses: azure/CLI@v1
        shell: bash
        with:
          azcliversion: latest
          inlinescript: |
            #!/bin/bash
            if(az group exists --name ${{ inputs.azureAppName }}); then
              echo "AppName=${{inputs.azureAppName}}" >> $GITHUB_OUTPUT
            else
              az group create --name ${{ inputs.azureGroupName }} --location ${{inputs.azureRegion }}
               echo "AppName=${{inputs.azureAppName}}" >> $GITHUB_OUTPUT
            fi
        id: resource_Group
      - name: Deploy Function App
        uses: azure/arm-deploy@v1
        with:
          template: ${{ inputs.bicepFilePath }}
          parameters: resourceGroupName=${{ needs.resource_Group.outputs.AppName}}
          scope: subscription
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az logout
            az cache purge
            az account clear
