name: Import Azure PowerShell Consumption Function App Using Bicep Template
on: [workflow_dispatch]

permissions:
  id-token: write
  content: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.run_number == 1
    steps:
     - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      - name: Deploy Azure Function Template
        uses: azure/arm-deploy@v1
        resourceGroupName: ${{env.AZURE_RESOURCEGROUP_NAME}}
        template: ./deploy/main.bicep
        parameters: 