name: "Deploy Function Apps"
on:
  workflow_dispatch:
    inputs:
      bicepFilePath:
        description: Path to the bicep file
        required: true
        default: .github/workflows/deployment/main.deploy.bicep
    branches:
      - [$default-branch]

env:
  appName: "AZITGFunctions" # set this to your function app name on Azure
  packagePath: "." # set this to the path to your function app project, defaults to the repository root

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v3
      - name: Run Bicep Linter
        run: az bicep build --file ${{ inputs.bicepFilePath }}
        shell: bash
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v3
      - name: Login to Azure AD
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true
      - name: Run ARM validation test
        uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number}}
          resourceGroup: TestAzureAction
          template: ${{ inputs.bicepFilePath}}
          parameters: environmentType=test
          deploymentMode: Validate
  build-and-deploy:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    environment: prod
    needs: validate
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true
      - name: "Update App Service Settings"
        uses: Azure/appservice-settings@v1
        id: settings
        with:
          app-name: ${{ env.appName}}
          app-settings-json: ${{ secrets.APPLICATION_SETTINGS }}
      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AappName}}
          package: ${{ env.packagePath }}
