name: "Create new Function App"

on:
  workflow_dispatch:
    inputs:
      bicepFilePath:
        description: Bicep Template. Path to the bicep file
        required: true
        default: "./deployment/main.deploy.bicep"
      regionName:
        description: Placeholder for the region
        default: "westus"
    branches:
      - master

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v3
      - name: Run Bicep Linter
        run: az bicep build --file ${{ inputs.bicepFilePath }}
        shell: bash

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Deploy Function App
        uses: azure/arm-deploy@v1
        id: deploy-app
        with:
          scope: subscription
          region: ${{inputs.regionName}}
          template: ${{ inputs.bicepFilePath }}
      - run: echo ${{ steps.deploy-app.outputs.functionAppName }} > /deployment/functionAppName.txt
      - name: Archive Function App Artifacts
        uses: actions/update-artifact@v3
        with:
          name: functionAppName
          path: deployment/artifacts/functionAppName.txt
      - name: "Update App Service Settings"
        uses: Azure/appservice-settings@v1
        id: settings
        with:
          app-name: ${{ steps.deploy-app.outputs.functionAppName }
          app-settings-json: ${{ secrets.APPLICATION_SETTINGS }}
      - name: Azure CLI script
        with:
          azcliversion: latest
          inlineScript: |
            az logout
            az cache purge
            az account clear
