name: Dump GitHub contexts to log file
on: workflow_dispatch

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
