name: "Update Function App on Pull"

on:
  workflow_dispatch:
    inputs:
      bicepFilePath:
        description: Path to the bicep file
        required: true
        default: .github/workflows/deployment/main.deploy.bicep
    branches:
      - master

env:
  appName: "AZITGFunctions" # set this to your function app name on Azure
  packagePath: "." # set this to the path to your function app project, defaults to the repository root

jobs:
  update-to-latest:
    runs-on: ubuntu-latest # For Linux, use ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true
      - name: "Update App Service Settings"
        uses: Azure/appservice-settings@v1
        id: settings
        with:
          app-name: ${{ env.appName}}
          app-settings-json: ${{ secrets.APPLICATION_SETTINGS }}
      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AappName}}
          package: ${{ env.packagePath }}
