name: "Update Function App on Pull"

on:
  workflow_dispatch:
    branches:
      - master

env:
  appName: "AZITGFunctions" # set this to your function app name on Azure
  packagePath: "." # set this to the path to your function app project, defaults to the repository root

jobs:
  update-to-latest:
    runs-on: ubuntu-latest # For Linux, use ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true
      - name: "Update App Service Settings"
        uses: Azure/appservice-settings@v1
        id: settings
        with:
          app-name: ${{ env.appName}}
          app-settings-json: ${{ secrets.APPLICATION_SETTINGS }}
      - name: Bicep Build
        uses: aliencube/bicep-build-actions@v0.3
        with:
          files: './deployment/main.deploy.bicep'
      # Checks the result
      - name: Check the result
        shell: bash
        run: |
          shopt -s globstar
          ls -altR **/main.deploy*.*
